// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnapvijysfckdjvyphvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uYXB2aWp5c2Zja2RqdnlwaHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxOTkzNjMsImV4cCI6MjA1ODc3NTM2M30.-BHt-StuwHfhjv2--ciHvAZrXoVI4DVA45J_kNi_Jfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);